//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCCS.LocalizedString.NetStandard.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCCS.LocalizedString.NetStandard.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Test Exception.
        /// </summary>
        internal static string DCCS_LocalizedString_NetStandard_Tests_ExceptionTests_TestException {
            get {
                return ResourceManager.GetString("DCCS_LocalizedString_NetStandard_Tests_ExceptionTests_TestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Test 1.
        /// </summary>
        internal static string DCCS_LocalizedString_NetStandard_Tests_LocalizerTest_MyTest_Test1 {
            get {
                return ResourceManager.GetString("DCCS_LocalizedString_NetStandard_Tests_LocalizerTest_MyTest_Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Test Second.
        /// </summary>
        internal static string DCCS_LocalizedString_NetStandard_Tests_LocalizerTest_MyTest_Test2 {
            get {
                return ResourceManager.GetString("DCCS_LocalizedString_NetStandard_Tests_LocalizerTest_MyTest_Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First: {0} Second: {1}.
        /// </summary>
        internal static string DCCS_LocalizedString_NetStandard_Tests_LocalizerTest_TestFormat {
            get {
                return ResourceManager.GetString("DCCS_LocalizedString_NetStandard_Tests_LocalizerTest_TestFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string DCCS_LocalizedString_NetStandard_Tests_LocalizerTest_TestString {
            get {
                return ResourceManager.GetString("DCCS_LocalizedString_NetStandard_Tests_LocalizerTest_TestString", resourceCulture);
            }
        }
    }
}
